name: generate contribution snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  snake:
    runs-on: ubuntu-latest

    steps:
      - name: generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: yuno7777
          outputs: |
            dist/github-contribution-grid-snake.svg?palette=github-light&color_snake=#000000
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=#ffffff

      - name: publish
        uses: crazy-max/ghaction-github-pages@v4
        with:
          build_dir: dist
        env:
          GH_PAT: ${{ secrets.GITHUB_TOKEN }}
